"""empty message

Revision ID: 00a8a030975b
Revises: e354689f2475
Create Date: 2019-01-12 08:08:33.063745

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '00a8a030975b'
down_revision = 'e354689f2475'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_account_username', table_name='account')
    op.drop_column('account', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('username', sa.VARCHAR(length=48), autoincrement=False, nullable=False))
    op.create_index('ix_account_username', 'account', ['username'], unique=True)
    # ### end Alembic commands ###
