"""empty message

Revision ID: 1b740b5eb1b0
Revises: 18172a54939d
Create Date: 2019-03-25 07:44:47.117086

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1b740b5eb1b0'
down_revision = '18172a54939d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account', 'role',
                    existing_type=sa.VARCHAR(length=64),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account', 'role',
                    existing_type=sa.VARCHAR(length=64),
                    nullable=True)
    # ### end Alembic commands ###
