"""empty message

Revision ID: 6edec41e10af
Revises: 1b740b5eb1b0
Create Date: 2019-03-25 07:49:20.101739

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '6edec41e10af'
down_revision = '1b740b5eb1b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account', 'role',
                    existing_type=sa.VARCHAR(length=64),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account', 'role',
                    existing_type=sa.VARCHAR(length=64),
                    nullable=False)
    # ### end Alembic commands ###
