"""empty message

Revision ID: 990fd519d2dc
Revises: 6edec41e10af
Create Date: 2019-03-25 13:22:15.930600

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '990fd519d2dc'
down_revision = '6edec41e10af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('authenticated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'authenticated')
    # ### end Alembic commands ###
