"""empty message

Revision ID: adc933806b98
Revises: ede2a144c27d
Create Date: 2019-01-06 19:09:52.268414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adc933806b98'
down_revision = 'ede2a144c27d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account', 'created_on',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('account', 'username',
               existing_type=sa.VARCHAR(length=48),
               nullable=True)
    op.alter_column('entry', 'account_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('entry', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('entry', 'created_on',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('entry', 'title',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('tag', 'created_on',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('tag', 'modified_on',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('tag', 'name',
               existing_type=sa.VARCHAR(length=48),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tag', 'name',
               existing_type=sa.VARCHAR(length=48),
               nullable=False)
    op.alter_column('tag', 'modified_on',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('tag', 'created_on',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('entry', 'title',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('entry', 'created_on',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('entry', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('entry', 'account_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('account', 'username',
               existing_type=sa.VARCHAR(length=48),
               nullable=False)
    op.alter_column('account', 'created_on',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
