"""empty message

Revision ID: c2471f4d6fca
Revises: 990fd519d2dc
Create Date: 2019-05-22 23:11:47.152896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2471f4d6fca'
down_revision = '990fd519d2dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('admin', sa.Boolean(), nullable=False))
    op.add_column('account', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.add_column('account', sa.Column('confirmed_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'confirmed_on')
    op.drop_column('account', 'confirmed')
    op.drop_column('account', 'admin')
    # ### end Alembic commands ###
