"""empty message

Revision ID: ede2a144c27d
Revises: 
Create Date: 2019-01-06 18:30:49.470023

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ede2a144c27d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_on', sa.Date(), nullable=False),
                    sa.Column('email', sa.String(length=120), nullable=True),
                    sa.Column('last_login', sa.Date(), nullable=True),
                    sa.Column('password_hash', sa.String(length=128), nullable=True),
                    sa.Column('username', sa.String(length=48), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_account_email'), 'account', ['email'], unique=True)
    op.create_index(op.f('ix_account_username'), 'account', ['username'], unique=True)
    op.create_table('tag',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_on', sa.Date(), nullable=False),
                    sa.Column('modified_on', sa.Date(), nullable=False),
                    sa.Column('name', sa.String(length=48), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('entry',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('account_id', sa.Integer(), nullable=False),
                    sa.Column('content', sa.Text(), nullable=False),
                    sa.Column('created_on', sa.Date(), nullable=False),
                    sa.Column('modified_on', sa.Date(), nullable=True),
                    sa.Column('title', sa.String(length=128), nullable=False),
                    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('tags',
                    sa.Column('tag_id', sa.Integer(), nullable=False),
                    sa.Column('entry_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['entry_id'], ['entry.id'], ),
                    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
                    sa.PrimaryKeyConstraint('tag_id', 'entry_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    op.drop_table('entry')
    op.drop_table('tag')
    op.drop_index(op.f('ix_account_username'), table_name='account')
    op.drop_index(op.f('ix_account_email'), table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
